### ISSUE TITLE
Alterar o título da Página

### ISSUE THREAD

**Issue by martim-lusofona** [DenivaldoAntonio/DenivaldoAntonio.github.io#5]
Alterar o título da Página, desta forma o utilizador consegue identificar a página nas tabs abertas e no histórico.

https://github.com/DenivaldoAntonio/DenivaldoAntonio.github.io/blob/bbdae2e77c9842f4e768b00c9691bb5df94de938/lab1/report.html#L7

**Comment by DenivaldoAntonio** [comment]
Alteração do title lab1
